version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app  # Монтируем локальную папку в контейнер

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Данные сохраняются между перезапусками

volumes:
  pgdata:
