"""add colomn color

Revision ID: 230addc55657
Revises: 174f02d3741b
Create Date: 2025-07-19 08:15:58.073302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230addc55657'
down_revision = '174f02d3741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('more_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ids', sa.String(length=30), nullable=True),
    sa.Column('old_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('color')

    op.drop_table('more_id')
    # ### end Alembic commands ###
