"""add_table_alternativeid

Revision ID: a80865140d02
Revises: 3ec171862cc4
Create Date: 2025-11-27 22:12:34.764346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80865140d02'
down_revision = '3ec171862cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternativeid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('color_key', sa.Integer(), nullable=True),
    sa.Column('alternative_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativeid')
    # ### end Alembic commands ###
